url: "https://charliemchapman.com"

title: "Charlie Chapman"
description: "The personal blog of Charlie Chapman."

logo: /assets/images/charlie-profile-2026.jpg

twitter:
  username: _chuckyc
  card: summary

social:
  name: Charlie Chapman
  links:
    - https://twitter.com/_chuckyc

collections:
  podcasts:
    output: true
    permalink: /podcasts/:slug/
  videos:
    output: true
    permalink: /videos/:slug/
  talks:
    output: true
    permalink: /talks/:slug/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /posts/:year/:i_month/:i_day/:title
      nav_key: "home"
  - scope:
      path: ""
      type: "podcasts"
    values:
      layout: "entry"
      nav_key: "home"
  - scope:
      path: ""
      type: "videos"
    values:
      layout: "entry"
      nav_key: "home"
  - scope:
      path: ""
      type: "talks"
    values:
      layout: "entry"
      nav_key: "home"
  - scope:
      path: "pages"
    values:
      permalink: /:basename/
  - scope:
      path: ""
    values:
      layout: "default"
      nav_key: "home"
      image: /assets/images/charlie-profile-2026.jpg

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
